### ISSUE TITLE
Teleport API

### ISSUE THREAD

**Issue by web-padawan** [webcomponents-cg/community-protocols#4] opened 2020-10-28 08:36 UTC
I would like to start a discussion regarding Teleport API aka unified overlay system for custom elements.

## Motivation

Some types of components, like full-screen modals, dropdown menus, popups etc, need the overlay system that helps to escape CSS stacking context introduced by other components where they are placed.

One common case is placing such components inside the infinite scrollers like `iron-list` or `vaadin-grid`.
See the related issues: https://github.com/PolymerElements/iron-list/issues/242 and  https://github.com/vaadin/vaadin-grid/issues/842

Currently pretty much every custom elements library has its own overlay system which means that trying to mix components from different libraries in the same app might introduce compatibility problems.

### Frameworks

- React Portals: https://reactjs.org/docs/portals.html
- Vue 3 Teleport: https://v3.vuejs.org/guide/teleport.html

### Web components

Note: the following list contains the implementations that I'm aware of, please feel free to add yours in the comments.

- [`iron-overlay`](https://github.com/PolymerLabs/iron-overlay)
- [`vaadin-overlay`](https://github.com/vaadin/vaadin-overlay)
- [Lion overlays](https://github.com/ing-bank/lion/tree/master/packages/overlays)
- [Elix OverlayMixin](https://github.com/elix/elix/blob/master/src/base/OverlayMixin.js)
- [JElements Portal](https://v0-4--jelements.netlify.app/util/portal)

## Goals

- Provide a low-level helper that could be used by libraries as well as vanilla custom element authors.
- Aim for a consistent developer experience and user experience across web components libraries.

**Comment by thepassle** [comment] 2020-10-28 09:00
[generic-components](https://github.com/thepassle/generic-components/tree/master/generic-dialog) uses this as well

**Comment by Westbrook** [comment] 2020-10-28 13:58
We also use some tooling for this in [Spectrum Web Components](https://github.com/adobe/spectrum-web-components/tree/main/packages/overlay/src).

A quick overview of these various implementations seem to point to two general approaches that I'd call "Throwing the overlay" (giving an element the power to place content into the `document`, or "Announcing the overlay" (dispatching an event so that something else can place content into the `document`). The main functional difference being the need for a sentinel listener (either in script or as an element itself) to be present in order to responds to the dispatched event. What are people's thought on whether the goals herein can be reached with either or not? Whether the two approaches can exist side by side (if we're able to outline a workable protocol) or not?

Separately, while I agree that a protocol is warranted here, I worry that even with things like `#elementInternals` et al we will continue to have a ceiling on what is possible here as far as accessibility. Would anyone else be interested in preparing and forwarding a `<teleport>` (yes "portal" was likely the right name, but...taken 😞) element spec to WHATWG in conjunction with this work?

**Comment by ryansolid** [comment] 2020-10-28 17:49
I struggled with this one a lot in the past. Especially didn't find any of the existing solution satisfactory. Things like event propagation and styling are definitely tricky.

From my experience the things I'm pretty sure you want here for playing nicely with Shadow DOM based styling is the Portal itself to be able to have a ShadowRoot at the mount point. Even if the inserted component has its own Shadow Root, it is common for components like Modals to pass in light DOM children that may carry their own styles. As soon as the Modal is in the Teleport those children are sort of orphaned from a styling sense.

I ended up making my Portals as part of the non-web component part of my library and just have the ability to create the mounted div with a ShadowRoot and then used my frameworks `props.children` mechanism to put all children in including styles. Using light dom slotting doesn't really help us as again those elements will be outside of the Shadow DOM. I found you would need to have the Portal consumer be able to pass in Style tags that will be inserted inside of the ShadowRoot of the mounting point.

Maybe that is all too complicated but I just adapted these approaches from what my previous company ended up doing. But some of it is probably outdated as we've been using Custom Elements in production since 2014. I just picture this structure:

```html
<teleport>
  <my-modal>
    <h1 slot="header">Title<h1>
    <p slot="content">Who is styling me?</p>
  </my-modal>
</teleport>
```

**Comment by Westbrook** [comment] 2020-10-28 23:20
@ryansolid We also encountered similar issues around themeing when developing the solution we use in the Spectrum Web Components, link above. Particularly with the content placed directly in the `<teleport>`ing element. We document an aversion to this, unless you specifically include a `<style>` tag in the `<teleport>`ing element in favor or a fully contained custom element. Not always that easy to ensure. However, all of our elements do conform to a theme strategy outlined by CSS Custom Properties that original in an `<sp-theme>` element created content. With the assumption that such a context might (should?) exist, we [resolve the settings of that context](https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/src/overlay.ts#L109) when available and create a duplicate of in our [`<active-overlay>` element](https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/src/ActiveOverlay.ts#L466) which holds all any overlaid content to ensure that content has the same theme context available.

_THIS_ is very specifically why I think a new element proposal would best serve all use cases (custom element and no) for this situation in a way that libraries/protocols/etc cannot...

**Comment by EisenbergEffect** [comment] 2021-01-29 16:45
Hey folks! I think everyone would benefit from this group taking a look at the new Popup proposal:

https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Popup/explainer.md

To provide feedback, feel free to create issues on the GitHub issue. [Here's a link that will configure the issue for you.](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/new?assignees=melanierichards%2C+BoCupp-Microsoft%2C+ipopescu93&labels=Popup&template=popup.md&title=%5BPopup%5D+%3CTITLE+HERE%3E)

This doesn't solve all the issues that a portal will, especially related to preserving style context and such, but it is a related proposed platform primitive for these types of scenarios.

**Comment by gregwhitworth** [comment] 2021-03-29 20:36
Adding on here - `<popup>` has officially been taken on by the Open UI community group so if you want to engage on that one head over there to open issues: https://github.com/WICG/open-ui

**Comment by Westbrook** [comment] 2023-11-04 14:26
With the advent of the `[popover]` API, closing this conversation!

**Closed by Westbrook** 2023-11-04 14:26 UTC
